apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-sample-app-dpl
  namespace: production
spec:
  selector:
    matchLabels:
      app: sample-app
      env: production
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
        env: production
    spec:
      containers:
      - name: go-sample-app
        image: asia-southeast2-docker.pkg.dev/dev-devsecops-prj/khhini-repository/go-sample-app:1.0
        ports:
        - containerPort: 8080