---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-sample-app-dpl
  namespace: staging
spec:
  selector:
    matchLabels:
      app: sample-app
      env: staging
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
        env: staging
    spec:
      containers:
      - name: go-sample-app
        image: asia-southeast2-docker.pkg.dev/dev-devsecops-prj/khhini-repository/go-sample-app:bca4a3c
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: go-sample-app-svc
  namespace: staging
spec:
  selector:
    app: sample-app
    env: staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
