steps:

- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials ${_CLOUDSDK_CONTAINER_CLUSTER} --zone ${_CLOUDSDK_COMPUTE_REGION}
    kubectl kustomize overlays/prod | kubectl apply -f -

substitutions:
  _CLOUDSDK_COMPUTE_REGION: asia-southeast2
  _CLOUDSDK_CONTAINER_CLUSTER: khhini-cluster
  _APP_NAME: sample-app
  _APP_VERSION: v1.1
  _APP_ROLE: backend
  _APP_IMAGE: asia-southeast2-docker.pkg.dev/dev-devsecops-prj/khhini-repository/go-sample-app:386248c
  _APP_GIT_COMMIT: "Relase v1.1 from image asia-southeast2-docker.pkg.dev/dev-devsecops-prj/khhini-repository/go-sample-app:386248c
      Built from commit https://github.com/khhini/riset-devsecops-sample-app/commit/b5daeec5b71ed80e88939dbb3c94afa748485ff8
      Author: $(git log --format='%an <%ae>' -n 1 HEAD)"
  _APP_STAGING_URL: staging-data.pencerahnusantara.org
