steps:

- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'kustomize'
  - 'overlays/stage'
  - '|'
  - 'kubectl'
  - 'apply'
  - '-f'
  - '-'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=asia-southeast2'
  - 'CLOUDSDK_CONTAINER_CLUSTER=khhini-cluster'
