steps:

- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - '-c'
  - |
    kubectl kustomize overlays/prod | kubectl apply -f -
  env:
  - 'CLOUDSDK_COMPUTE_REGION=asia-southeast2'
  - 'CLOUDSDK_CONTAINER_CLUSTER=khhini-cluster'
