steps:

- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials ${_CLOUDSDK_CONTAINER_CLUSTER} --zone ${_CLOUDSDK_COMPUTE_REGION}
    kubectl kustomize overlays/stage | kubectl apply -f -

substitutions:
  _CLOUDSDK_COMPUTE_REGION: asia-southeast2
  _CLOUDSDK_CONTAINER_CLUSTER: khhini-cluster