resources:
- ../../base

namespace: staging
patches:
- target:
    kind: Deployment
    name: go-sample-app-dpl
  patch: |
    - op: replace
      path: /spec/selector/matchLabels/env
      value: staging
    - op: replace
      path: /spec/template/metadata/labels/env
      value: staging
- target:
    kind: Service
    name: go-sample-app-svc
  patch: |
    - op: replace
      path: /spec/selector/env
      value: staging
images:
- name: asia-southeast2-docker.pkg.dev/dev-devsecops-prj/khhini-repository/go-sample-app
  newTag: "1.0"