apiVersion: v1
kind: Service
metadata:
  name: go-sample-app-svc
  namespace: kustomize
spec:
  selector:
    app: sample-app
    env: kustomize
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
